# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddproducttoacard():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addproducttoacard(self):
    self.driver.get("https://bookshop.org/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.XPATH, "//input[@name=\'keywords\']").click()
    self.driver.find_element(By.XPATH, "//input[@name=\'keywords\']").send_keys("Sherlock Holmes")
    self.driver.find_element(By.XPATH, "//img[@alt=\'Search\']").click()
    self.driver.find_element(By.XPATH, "//img[contains(@src,\'https://images-us.bookshop.org/ingram/9781802792546.jpg?height=250&v=v2\')]").click()
    self.driver.find_element(By.XPATH, "//img[contains(@src,\'https://rails-assets-us.bookshop.org/assets/ic_cart_light-b26a46b06b6ae40a9499157d18cb2eba8f8d81b0de5637f93ef851ea54ceae4c.svg\')]").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'check out\n        (1 item)\')]").click()
    self.driver.find_element(By.XPATH, "//input[@id=\'order_line_items_attributes_0_quantity\']").click()
    self.driver.find_element(By.XPATH, "//input[@id=\'order_line_items_attributes_0_quantity\']").send_keys("2")
    self.driver.find_element(By.XPATH, "//input[@id=\'order_line_items_attributes_0_quantity\']").click()
    self.driver.find_element(By.XPATH, "//button[@id=\'checkout-link\']").click()
    self.driver.find_element(By.XPATH, "//img[@alt=\'Shopping Cart\']").click()
    self.driver.find_element(By.XPATH, "(//img[contains(@src,\'https://rails-assets-us.bookshop.org/assets/ic_trash-c72efaf6e64b288202ce98c774e7edf643dbe615629bb091f8534be1664f707b.svg\')])[2]").click()
  
